### ISSUE TITLE
VPS non-unique names result in misleading TF-state

### ISSUE THREAD

**Issue by JoooostB** [aequitas/terraform-provider-transip#19]
When creating a new VPS with the same name as one that already exists in your account, TransIP's API returns the unique-ID of the pre-existing VPS instead of the newly created one. This results in a `terraform.tfstate` that contains the ID of the old VPS. When doing new changes, you'll be modifying the wrong VPS.

**Comment by aequitas** [comment]
As discussed privately, I'll look into this to see if there is logic that needs to be adjusten on our side. I'll also write a testcase that will verify this situation.
