### ISSUE TITLE
Migrating to standalone SDK

### ISSUE THREAD

**Issue by kevinvalk** [aequitas/terraform-provider-transip#21]
During my work on #20, I came across https://www.terraform.io/docs/extend/plugin-sdk.html

It boils down to a simple change of `github.com/hashicorp/terraform` to `github.com/hashicorp/terraform-plugin-sdk`. This enables Terraform to decouple their core from the provider SDK.

**Comment by aequitas** [comment]
I havn't gotten around to this yet, but will probably pick this up soon.
