### ISSUE TITLE
Where to go from here

### ISSUE THREAD

**Issue by kevinvalk** [aequitas/terraform-provider-transip#25]
Hi @aequitas, I was wondering what your plans are for this terraform provider. I took the liberty to make some significant changes in the structure (work in progress for testing) to make it easier to test and release new version (see https://github.com/kevinvalk/terraform-provider-transip).

So I was wondering, where to go from here, do you want to merge it all back into your repository, or what shall we do?

**Comment by aequitas** [comment]
Sorry for the delay and lack of response.

I will merge your prs later today or beginning next week and get a release out.

**Comment by kevinvalk** [comment]
No problem!

Please have a look around at my changes in https://github.com/kevinvalk/terraform-provider-transip master branch.
- Structure changes
- Usage of GitHub actions to build releases on tag
- Etc

If you okay with those kind of changes. Would you be okay to give me access to this repository so I can work directly on this repository?

**Comment by aequitas** [comment]
I’m a little tied up at the moment but if I get a chance later today or tomorrow i will have a look.

**Comment by kevinvalk** [comment]
Sure no hurries, I am fine with working on my fork. Just thinking about other users and the future.

**Comment by aequitas** [comment]
Biggest problem right now is the cost for testing against the real transip api. But that might be solved soon. I’ll keep you posted on that.

**Comment by kevinvalk** [comment]
Definitely, I am also having some conversations with Transip about that.

**Comment by aequitas** [comment]
I merged your previous PR's and release it together with previous changes: https://github.com/aequitas/terraform-provider-transip/releases/tag/0.1.2

I'm not confortable with giving anybody direct access to my repositories but feel free to make contributions.

I'll have a look into incorporating the release action, but I don't feel like dropping the Makefile workflow.
