### ISSUE TITLE
DNS records id will break when changing name

### ISSUE THREAD

**Issue by kevinvalk** [aequitas/terraform-provider-transip#27]
Whenever you change the name of a DNS record resource, terraform will get confused. This is due to the fact that the ID contains the name field.

We should probably just set force new on name, that way we remove the record and create a new one.

**Comment by aequitas** [comment]
That would probably be the easiest way. I'll write a test for this scenario and add the forcenew flag.

**Comment by aequitas** [comment]
Fixed in https://github.com/aequitas/terraform-provider-transip/commit/2da74e342e2635351ecc690df8a76037de5e75ea
