### ISSUE TITLE
Failed to create token cache dir

### ISSUE THREAD

**Issue by nielsvbrecht** [aequitas/terraform-provider-transip#40]
Hi all,

I have been happily using the transip tf provider for some time now and have placed all my private dns zones in terraform config files. 
On my chromebook using VS Code on Linux (actually also a  (LXC) container on ChromeOS) it works fine and I can do whatever I need to do. But I want to automate my deployment through Gitlab which runs the code from a container. When running it in the pipeline and terraform wants to start using the transip provider it provides me with the following error:

 Error: failed to create token cache dir
│ 
│   with provider["registry.terraform.io/aequitas/transip"],
│   on main.tf line 6, in provider "transip":
│    6: provider "transip" {

I have used an access_token with the provider as well as private_key which are loaded from environment variables TRANSIP_ACCESS_KEY or TRANSIP_PRIVATE_KEY (incl TF_VAR_transip_private_key etc.)

This is in my main.tf for the transip provider which I have expanded with access_token or private_key. I am using version 0.1.7 of the provider.

provider "transip" {
  account_name = var.transip_account_name
}

Both result in the same error within a container (hashicorp/terraform:0.14.11 and 0.15.3)

I cannot find anything related to this error where it would be coming from, so hopefully someone can guide me on this issue. Probably overlooking something...

**Comment by aequitas** [comment]
the provider determines the token dir via https://github.com/aequitas/terraform-provider-transip/blob/985ba72c906ee38b4a35633536787a9d27e986b6/provider.go#L99-L109

So either the https://golang.org/pkg/os/#UserCacheDir or https://golang.org/pkg/os/#TempDir as fallback.

The container has probably neither of these set or the container user doesn't have permission to create the required files there?

Hope this helps.

**Comment by nielsvbrecht** [comment]
Totally forgot to check the source code! Setting the XDG variable did the trick! Thanks
