### ISSUE TITLE
The provider provider.transip does not support resource type "transip_sshkey".

### ISSUE THREAD

**Issue by brutesque** [aequitas/terraform-provider-transip#42]
I found in the code that transip_sshkey should be an available resource. But when configuring it in the terraform configs, i get the mentioned error.

Is this resource not implemented yet in version 0.1.7?

**Comment by aequitas** [comment]
It was not released yet, I pushed https://github.com/aequitas/terraform-provider-transip/releases/tag/v0.1.8 just now.
