### ISSUE TITLE
Error: failed to read DNS record entries for domain somedomain.nl: could not get token from authenticator: error requesting token: The label 'gotransip-client-1631305153' is already used in another active access token.

### ISSUE THREAD

**Issue by Jille** [aequitas/terraform-provider-transip#44]
I'm trying to use terraform-provider-transip to add a few DNS records to my domain, but I'm getting this error:

```
Error: failed to read DNS record entries for domain somedomain.nl: could not get token from authenticator: error requesting token: The label 'gotransip-client-1631305153' is already used in another active access token.
```

If I run it again, I get the same error with another timestamp in the label.

I'm trying to add 4 domain names at once, and I'm getting this error 3 times.  None of them are added to DNS though.

**Comment by aequitas** [comment]
Maybe something changes on the Transip side in how they handle concurrent requests. DNS always has been a little finicky with concurrency as you need to replace the entire DNS zone and cannot make changes to single records at a time.

I'll need to investigate this and try to replicate.

As a mitigation, could you try running Terraform with parallelism set to 1 (https://www.terraform.io/docs/cli/commands/apply.html#parallelism-n), this is a little slower but might solve the issue for now.

**Comment by Jille** [comment]
Did you see the pull request I linked? It seems that calling the authenticator twice in the same second causes this problem.

I suppose that ideally terraform-provider-transip would create the authenticator only once and reuse that?

I wanted to try that, but Terraform Cloud doesn't support it :/

**Comment by aequitas** [comment]
You didn't mention you where running in Terraform Cloud or you where running multiple instances of apply at the same time so I had to guess what was going on. Within the same Terraform plan/apply the authenticator is only called once and reused for every action. But concurrent runs might be a problem indeed.

**Comment by Jille** [comment]
Apologies.

I'm running only a single apply at the same time, using Terraform cloud. My config does include multiple transip_dns_record's however.

**Comment by aequitas** [comment]
I'd have to run a test inside Terraform Cloud to replicate this. I don't know if Terraform Cloud does anything special regarding concurrency. I'll get back to you on this. 

I can't find an easy way to set parallelism in Terraform Cloud so I don't have a short term workaround for now I'm afraid.

**Comment by Jille** [comment]
I had emailed TFC support and they pointed me at the documentation (https://www.terraform.io/docs/cloud/workspaces/variables.html#special-environment-variables). Reducing the parallelism solved the issue.

I got my bugfix upstreamed just now, so I opened PR #45 to update gotransip.

Feel free to close this once that's merged, or to keep it open if you want to investigate why the authenticator runs multiple times despite that it shouldn't.

Thanks for your help :)

**Comment by aequitas** [comment]
That was quick, I've merged your PR, will push an update out later this evening.

**Comment by aequitas** [comment]
https://github.com/aequitas/terraform-provider-transip/releases/tag/v0.1.10 

Thanks for helping out.

**Comment by Jille** [comment]
Thanks for the quick responses, merge and release! :)
