### ISSUE TITLE
Add datasource for all domains

### ISSUE THREAD

**Issue by WebSpider** [aequitas/terraform-provider-transip#48]
When using the kubernetes external-dns feature, to automatically update DNS providers (one of the supported ones is TransIP), it is very useful to have a list of domainnames currently in the account.

The TransIP API has a call for this:
https://api.transip.nl/rest/docs.html#domains-domains-get

This is a request to add this data as a datasource, so the data is accessible in terraform.

**Comment by aequitas** [comment]
Can you give an example how you would use this resource in your code?

**Comment by WebSpider** [comment]
Absolutely!

```
data "transip_domains" "all_domains" {
}

resource "helm_release" "external-dns-transip" {
  name = "edns-transip"
  namespace = "kube-system"
  repository = "https://charts.bitnami.com/bitnami"
  chart = "external-dns"
  version = "5.4.16"

  set {
    name = "transip.account"
    value = var.transip_account
  }
  set {
    name = "provider"
    value = "transip"
  }
  set_sensitive {
    name = "transip.apiKey"
    value = var.transip_privkey
  }
  set {
    name = "txtOwnerId"
    value = var.dns_txt
  }
  set {
    name = "domainFilters"
    value = "{${join(",", data.transip_domains.all_domains)}}"
  }
}
```

**Comment by JoooostB** [comment]
With latest release v0.1.12 you're now able to do the following:
```tf
data "transip_domains" "all_domains" {
}

...
value = "{${join(",", data.transip_domains.domains)}}"
...
```
Hope this helps @WebSpider

**Comment by WebSpider** [comment]
Much thanks, I will try this and report back if any issues! :+1:
