### ISSUE TITLE
Publish v0.1.12 to registry

### ISSUE THREAD

**Issue by WebSpider** [aequitas/terraform-provider-transip#50]
Hi!
After testing with #49 in the v0.1.12 of this provider, I noticed this version hadn't been published to terraform's registry. Could this be done?
On the upside, I figured out how to locally load providers that are not in the registry \o/

**Comment by aequitas** [comment]
That should happen automatically, but it didn't last time i guess. I resynced the registry entry for this project, should be fixed now: https://registry.terraform.io/providers/aequitas/transip/0.1.12
