### ISSUE TITLE
Terraform apply Error: Failed to set ID for VPS and takes to much time

### ISSUE THREAD

**Issue by pabl-o-ce** [aequitas/terraform-provider-transip#58]
Hi guys, great work

I was using Terraform for create vm's in TransIP

All works beautiful the first time

then I destroy and try again to create and it take to much time and also end with this error
```Error: Failed to set ID for VPS ```

my instance resource look like this:
```terraform
# Workshop defender instance
resource "transip_vps" "crowdsec_instance_defender" {
  # Add number of instances
  count                         = var.tsp_number_of_instances
  # Availability zone
  availability_zone             = "rtm0"
  # Add instances type
  product_name                  = "vps-bladevps-xs"
  # Add image type
  operating_system              = "ubuntu-22.04"
  # Add cloud-init on user-data folder
  install_text                  = file("${path.module}/user-data/workshop-blank.yml")
  # Add description name
  description                   = (count.index<9) ? "defender0${(count.index+1)}" : "defender${(count.index+1)}"
}
```
is something I'm doing wrong?

**Comment by JoooostB** [comment]
After initiating the `terraform apply` again, were the instances created/visible in the TransIP dashboard prior to receiving the `Failed to set ID for VPS` error? I'm a bit lost on which side this issue arises, as we only throw this error when no unique name can be retrieved from TransIP.

**Comment by pabl-o-ce** [comment]
I will get you some pictures in here:
step 1: [success]
```terraform plan -var-file="terraform.tfvars"``` 
step 2: [fails]
```terraform apply -var-file="terraform.tfvars"``` 

in this step I was receiving  this `Error: Failed to set ID for VPS` from like 30 minutes of waiting for creating the vm's
now I only receive a quick response show in the photo above:

<img width="1031" alt="Screen Shot 2022-08-07 at 11 48 54 AM" src="https://user-images.githubusercontent.com/4999086/183301933-f5e809cc-63f9-448a-856a-b8ae54a3014a.png">

mmm... sound some issues with the account?

**Comment by JoooostB** [comment]
> mmm... sound that have some issues with the account?

I'm afraid so, worth trying to create a VPS using the REST API directly:
```bash
curl -X POST \
-H "Content-Type: application/json" \
-H "Authorization: Bearer [your JSON web token]" \
-d '
{
  "productName": "vps-bladevps-xs",
  "availabilityZone": "rtm0",
  "description": "defender01",
  "operatingSystem": "ubuntu-22.04",
  "installFlavour": "installer"
} 
' \
"https://api.transip.nl/v6/vps"
```
If that doesn't work either you've a create case to contact TransIP support. Please report back your findings, I'm rather interested in what exactly went wrong here :)

**Comment by aequitas** [comment]
Maybe it's a race condition where the older VPS with the same name is still lingering on the Transip API side. Creating a new VPS with the same name could maybe create a conflict then. I think this problem is reproducable on my side, maybe even possible to write a test for it. I'll have a look tomorrow.

**Comment by JoooostB** [comment]
I thought about that, but isn't the name generated by them in the `username-vpsxxxx` format? As we only set the description and need to lookup the name afterwards.

**Comment by pabl-o-ce** [comment]
> I think this problem is reproducable on my side, maybe even possible to write a test for it.

If you one I can create what I made in a repo so you can test it on your side with your accounts

> I'm afraid so, worth trying to create a VPS using the REST API directly

The token from what I read is generate from the contro panel website... right? sorry I'm new on TransIP

**Comment by pabl-o-ce** [comment]
this is the repo: https://github.com/pabl-o-ce/transip-test
If you need it :)

**Comment by pabl-o-ce** [comment]
Also I reproduce the same error with 20 minutes of delay:

<img width="1019" alt="Screen Shot 2022-08-08 at 10 22 48 AM" src="https://user-images.githubusercontent.com/4999086/183453905-5add8092-9dba-4f22-b3d5-290ff656dc5f.png">

**Comment by pabl-o-ce** [comment]
seems to be a problem of the account guys sorry for the noise.. it was not filled out all information required :)

All works great now [amazing]

Thanks for the support
