### ISSUE TITLE
Use new REST API

### ISSUE THREAD

**Issue by aequitas** [aequitas/terraform-provider-transip#6]
https://www.transip.nl/nieuws/de-nieuwe-transip-rest-api-is-live/

- Individual DNS record changes.
- VPS provisioning scripts.
- Tags.

Enough reasons to consider switching to the REST API.

No Go library is yet published. Current Go library still uses SOAP/XML.

**Comment by kevinvalk** [comment]
Transip released the new Go library https://github.com/transip/gotransip.

Did you already start working on the migration? Perhaps I can help.

**Comment by aequitas** [comment]
https://github.com/transip/gotransip/issues/26

Already working on this :). But due to the nice weather I've not had much time behind my computer past weeks.

I'm trying to push an initial version later today, if you want to help testing it would be great.

**Comment by kevinvalk** [comment]
Definitely, let me know when you push.

**Comment by aequitas** [comment]
https://github.com/aequitas/terraform-provider-transip/pull/10

**Comment by aequitas** [comment]
https://github.com/aequitas/terraform-provider-transip/releases/tag/0.1.1
