### ISSUE TITLE
New release for cloud-init support

### ISSUE THREAD

**Issue by StanvanHoorn** [aequitas/terraform-provider-transip#62]
Hi, 

I can see that you added support for the install_flavour flag in [master](https://github.com/aequitas/terraform-provider-transip/commit/2d7fe82d9a2704dce30cbec460573c76d9dd4235) but didn't publish a new release yet.

Is the install_flavour flag tested and do you plan to create a new release?

Thanks!

**Comment by aequitas** [comment]
I probably forgot, new release is available: https://github.com/aequitas/terraform-provider-transip/releases/tag/v0.1.17

**Comment by StanvanHoorn** [comment]
Awesome, thanks!
