### ISSUE TITLE
Cannot authenticate to TransIP anymore.

### ISSUE THREAD

**Issue by gregoryca** [aequitas/terraform-provider-transip#77]
Currently i'm using the: account_name and private_key set in the transip provider.
Today i suddenly started receiving errors while logging in. 

It said: **failed to lookup domain "x": Your access token has been revoked.** 

So i contacted support because i did not revoke my authentication token and they asked me if i'm using the correct headers when authenticating to TransIp.

My question is how should i use the correct header when using the provider ?
Can i set:

account_name = account name
private_key = << EOT
private key
EOT
access_token = << EOT
accesstoken
EOT

Thanks for the help !

**Comment by aequitas** [comment]
You don't need to specify the token if you use a private key in the config. The provider will request a temporary token for you and cache it. Maybe that cached token is expired. You can find it as `$XDG_CACHE_HOME/gotransip_test_token_cache` or `$HOME/Library/Caches/gotransip_test_token_cache`, depending on your OS. Can you delete that file and try again?

**Comment by gregoryca** [comment]
Thank you so much for your quick answer ! it was indeed the cached token that was expired.
The folder location was $HOME/.cache/gotransip_test_token_cache.

Is there for example a best practices i can use to automate the creation of the new token ?
