### ISSUE TITLE
Failed to instantiate provider "transip" to obtain schema

### ISSUE THREAD

**Issue by koesper** [aequitas/terraform-provider-transip#9]
Hi!
I'm successfully using this provider to provision stuff from my development machine, but now i'm trying to run it from a Google Cloud Shell environment.

But then I get this error:
`Error: Failed to instantiate provider "transip" to obtain schema: fork/exec /home/casper/.terraform.d/plugins/terraform-provider-transip_v0.0.7: exec format error`

When searching, this seems to be a [common](https://github.com/runatlantis/atlantis/issues/690) [problem](https://github.com/alexkappa/terraform-provider-auth0/issues/175) [with](https://www.x-cellent.com/blog/cgo-bindings/) [terraform](https://stackoverflow.com/a/41128211/93169) providers, when running on a Alpine based docker image.

Anyone any ideas how to work around this? I wasnt really ready for building my own Docker container :-(

**Comment by aequitas** [comment]
Could you verify you are using the linux binary and not the darwin one in Alpine? 

When I try to test this locally the plugin seems to run fine in Alpine, so I can't directly reproduce it:

```
$ make build/linux_amd64/terraform-provider-transip_v0.0.7
mkdir -p build/linux_amd64; GOOS=linux go build -o build/linux_amd64/terraform-provider-transip_v0.0.7
$ 
docker run -ti --rm -v $PWD:/src --workdir /src alpine build/linux_amd64/terraform-provider-transip_v0.0.7
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically
```

**Comment by koesper** [comment]
oh nooo! you are correct, i'm using the wrong binary.
Case closed, please replace user and try again :-)
